/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package browsermator.com;

import java.awt.event.ActionListener;


/**
 *
 * @author pcalkins
 */
public class Upload_File_Dialog extends javax.swing.JFrame {

    /**
     * Creates new form Upload_File_Dialog
     */
    String filename = "";
    
    
    public Upload_File_Dialog(String in_Filename) {
        super("Upload Browsermation File");
        initComponents();
        this.setVisible(true);
     //   this.setSize(800,400);
        this.filename = in_Filename;
       jTextFieldFilename.setText(filename);
       jLabelFailWarning.setVisible(false);
        
    }
    public void setshowWarningMessage(String message)
    {
        jLabelFailWarning.setText(message);
        jLabelFailWarning.setVisible(true);
    }
    public void setUpButtonText(String text)
    {
        jButtonUploadFile.setText(text);
    }
    public void hideWarningMessage()
    {
        jLabelFailWarning.setVisible(false);
    }
    public String getFilename()
    {
        return jTextFieldFilename.getText();
    }
    public String getDescription()
    {
        return jTextPaneDescription.getText();
        
    }
    public void addjButtonUploadFileActionListener(ActionListener listener)
{
    jButtonUploadFile.addActionListener(listener);
}
   public String getPrivate()
   {
      boolean checked = this.jCheckBoxPrivate.isSelected();
   if (checked)
   {
       return "1";
   }
   else
   {
       return "0";
   }
   
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFilename = new javax.swing.JLabel();
        jTextFieldFilename = new javax.swing.JTextField();
        jLabelDescription = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneDescription = new javax.swing.JTextPane();
        jButtonUploadFile = new javax.swing.JButton();
        jLabelFailWarning = new javax.swing.JLabel();
        jCheckBoxPrivate = new javax.swing.JCheckBox();
        jLabelUploadInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelFilename.setText("Filename:");

        jLabelDescription.setText("Description:");

        jScrollPane1.setViewportView(jTextPaneDescription);

        jButtonUploadFile.setText("Upload File");

        jLabelFailWarning.setText("*Filename entered has already been used, or the file is corrupt.");

        jCheckBoxPrivate.setText("Make Private (only accessible by you)");

        jLabelUploadInfo.setText("Max filesize: 1.5 megs.  All email information and password type fields will be removed during upload.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabelFilename))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelDescription)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelUploadInfo)
                    .addComponent(jButtonUploadFile, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxPrivate)
                    .addComponent(jLabelFailWarning)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFilename, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFilename)
                    .addComponent(jTextFieldFilename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabelFailWarning)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDescription))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonUploadFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxPrivate)
                .addGap(18, 18, 18)
                .addComponent(jLabelUploadInfo)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonUploadFile;
    private javax.swing.JCheckBox jCheckBoxPrivate;
    private javax.swing.JLabel jLabelDescription;
    private javax.swing.JLabel jLabelFailWarning;
    private javax.swing.JLabel jLabelFilename;
    private javax.swing.JLabel jLabelUploadInfo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldFilename;
    private javax.swing.JTextPane jTextPaneDescription;
    // End of variables declaration//GEN-END:variables
}
